FROM python:slim

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y git nodejs npm bash cmake make g++ time 

RUN git clone --recursive https://github.com/vgteam/odgi.git

RUN cd odgi && cmake -DBUILD_STATIC=1 -H. -Bbuild && cmake --build build -- -j 3

EXPOSE 3001

ENTRYPOINT ["odgi", "server", "-p", "3001", "-a", "0.0.0.0", "-i"]
